### ISSUE TITLE
Segfault in package using Nemo with MP integers

### ISSUE THREAD

**Issue by defeo** [Nemocas/Nemo.jl#790]
This simple module causes a segfault when in a Julia package (not if it is included in the REPL, though, so it's likely related to compilation):

```julia
module Bug

import Nemo: ZZ

export x

x = ZZ(2)^62

end # module
```

to trigger the segfault, load `Bug` and try to display `x`:

```
julia> using Bug

Welcome to Nemo version 0.16.2

Nemo comes with absolutely no warranty whatsoever


julia> x

signal (11): Segmentation fault
in expression starting at REPL[3]:0
__gmpz_size at /usr/bin/../lib/libgmp.so (unknown line)
fmpz_get_str at /workspace/srcdir/flint2/fmpz/get_str.c:34
base at /home/defeo/.julia/packages/Nemo/LBWHq/src/flint/fmpz.jl:1551
dec at /home/defeo/.julia/packages/Nemo/LBWHq/src/flint/fmpz.jl:1537 [inlined]
string at /home/defeo/.julia/packages/Nemo/LBWHq/src/flint/fmpz.jl:228 [inlined]
show at /home/defeo/.julia/packages/Nemo/LBWHq/src/flint/fmpz.jl:230 [inlined]
show at ./multimedia.jl:47
...[output truncated]
```

if I change the definition to `x = ZZ(2)^61`, the segfault goes away.

Using Nemo v0.16.2 in Julia 1.3.1 on Arch. I'm copying `Manifest.toml` for completeness.

```toml
# This file is machine-generated - editing it directly is not advised

[[AbstractAlgebra]]
deps = ["InteractiveUtils", "LinearAlgebra", "Markdown", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "941d2cfb0fab4e6bb976bbe576f56f724e5a8d20"
uuid = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
version = "0.8.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinaryProvider]]
deps = ["Libdl", "SHA"]
git-tree-sha1 = "5b08ed6036d9d3f0ee6369410b830f8873d4024c"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.8"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Nemo]]
deps = ["AbstractAlgebra", "BinaryProvider", "InteractiveUtils", "Libdl", "LinearAlgebra", "Markdown", "Random", "Test"]
git-tree-sha1 = "bdef7f0f78397fb75beef92fd9ad6cee5c448942"
uuid = "2edaba10-b0f1-5616-af89-8c11ac63239a"
version = "0.16.2"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
```
